// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7_SA-EjThNNqRHrwQiDamun8dLRzcuqQ',
    appId: '1:834121133893:web:0cd0de35c058efec5b182c',
    messagingSenderId: '834121133893',
    projectId: 'leafsnap-5eb2c',
    authDomain: 'leafsnap-5eb2c.firebaseapp.com',
    storageBucket: 'leafsnap-5eb2c.firebasestorage.app',
    measurementId: 'G-3VE31Q73D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4W7n_mqKKJo8LcqQRzgUEiULO9Mkvd8Y',
    appId: '1:834121133893:android:7cceeff9be0001e05b182c',
    messagingSenderId: '834121133893',
    projectId: 'leafsnap-5eb2c',
    storageBucket: 'leafsnap-5eb2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWsyuZxNZGuKlJJFOPDFD-P079SklIEkg',
    appId: '1:834121133893:ios:3bde8219d874367b5b182c',
    messagingSenderId: '834121133893',
    projectId: 'leafsnap-5eb2c',
    storageBucket: 'leafsnap-5eb2c.firebasestorage.app',
    iosBundleId: 'com.example.leafsnapAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWsyuZxNZGuKlJJFOPDFD-P079SklIEkg',
    appId: '1:834121133893:ios:3bde8219d874367b5b182c',
    messagingSenderId: '834121133893',
    projectId: 'leafsnap-5eb2c',
    storageBucket: 'leafsnap-5eb2c.firebasestorage.app',
    iosBundleId: 'com.example.leafsnapAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7_SA-EjThNNqRHrwQiDamun8dLRzcuqQ',
    appId: '1:834121133893:web:078b69008cc02eef5b182c',
    messagingSenderId: '834121133893',
    projectId: 'leafsnap-5eb2c',
    authDomain: 'leafsnap-5eb2c.firebaseapp.com',
    storageBucket: 'leafsnap-5eb2c.firebasestorage.app',
    measurementId: 'G-6G0XZGPGKW',
  );
}
